### ISSUE TITLE
Cannot load the pack through Curse, Out of memory exception

### ISSUE THREAD

**Issue by Trisscar05** [jadedcat/AS2Configs#1]
Extent of likely relevant crash log.
I should note that I'm using WinXP 64bit, and that I've been able to use FTB without this issue, though that may be because I can limit memory to 4 gigs there.

```
[13:35:32] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-1" Exception in thread "AWT-Windows" 
```

Edit (shadowfacts): Formatting

**Comment by shadowfacts** [comment]
After launching AS2 from Curse Voice, the Minecraft launcher should open. You'll need to open the profile editor and add the `-Xmx4G` option to the JVM arguments field (you may need to enable it first) to set the amount of RAM used to 4 gigs.

**Comment by Trisscar05** [comment]
Yup, that fixed it. Thank you surrah. :)

**Comment by Trisscar05** [comment]
I should add, since I've only confirmed it recently, that the added bit of code is reset every time the pack is opened through Curse, meaning that I must copy/pasta it back onto the end of the line each time. No idea which end is causing this, but fair warning to anyone else who uses this method.

**Comment by pjfranke** [comment]
I meant to comment earlier when I first saw this issue to add a picture to this to explain better, sorry for the delay.  Any changes made in the Minecraft launcher that the Curse launcher launches, will not stick. You need to edit them in the Curse launcher's Minecraft options here: http://puu.sh/jrcbp/dc9f60142d.png

My path is different, so disregard that.  3GB I've found to be plenty for all the packs I play, without using any resource packs.
