### ISSUE TITLE
AS2 mods not loading

### ISSUE THREAD

**Issue by 2000jf** [jadedcat/AS2Configs#152]
I am using AS2 1.1.14 and i can see in the log that following mods dont get started properly:
Ex Nihilo, Ex Astris, CustomNPC's, ExtraTiC, FinndusFiles, FlatSigns, WitchingGadgets
looks like it has something to do with CodeChickenCore
I already replaced Ex nihilo by a newer Version cause its necessary and it worked, but i cant update a mod like Ex Astris cause its on newest version and also replacing is annoying cause I'm playing on a self-hosted server with some friends.
The Error is always nearly the same: 

[Server thread/DEBUG] [FML/]: Examining file Ex-Astris-MC1.7.10-1.16-36.jar for potential mods
[18:00:18] [Server thread/WARN] [FML/]: Zip file Ex-Astris-MC1.7.10-1.16-36.jar failed to read properly, it will be ignored
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_71]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.7.0_71]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.7.0_71]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.7.0_71]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.7.0_71]
	at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:41) [JarDiscoverer.class:?]
	at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
	at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
	at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:131) [ModDiscoverer.class:?]
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:364) [Loader.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:489) [Loader.class:?]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by shadowfacts** [comment]
It looks like the mods were corrupted during the download. Try redownloading the pack. From the snippet of the log that you posted, there is nothing indicating that CodeChickenCore was involved.

**Comment by cblair91** [comment]
Assuming @shadowfacts fixed the problem. Closing.
