### ISSUE TITLE
ClassNotFoundException Error

### ISSUE THREAD

**Issue by Blackmak** [jadedcat/AS2Configs#189]
Whenever I try to launch the game, I get this error message:

[22:06:40] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:06:40] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

**Comment by cblair91** [comment]
Sounds like a forge not loading bug.

Have you tried uninstalling and reinstalling the modpack?

**Comment by Blackmak** [comment]
Multiple times.

**Comment by Trisscar05** [comment]
Sounds like you should try a different download location then, just in case something about the transit or copy from your current one is being silly.
Also, could we get basic computer specs and Java version and such?

**Comment by Blackmak** [comment]
Processor	Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
Manufacturer	Intel
Speed	1.8 GHz
Number of Cores	2
Video Card	Intel(R) HD Graphics 4000
Chipset	Intel(R) HD Graphics 4000
Dedicated Memory	96.0 MB
Total Memory	1.8 GB
Memory	8.0 GB
Operating System	Microsoft Windows 10 (build 10586), 64-bit
Service Pack	0
Size	64 Bit

Java version 8.0 update 71

**Comment by Trisscar05** [comment]
Hum. Ok, I'mma suggest that you try a different launcher, for example I think the Technic launcher carries it. I think this problem has been encountered and fixed with this before, if I remember my experience with trying Horizons correctly. Sometimes Curse doesn't play well with your computer on certain packs for some weird reason.

**Comment by Developaws** [comment]
Corrupted forge installation;

1. Write down minecraft version(we need forge version later) pack uses
2. Click `(...)` button
3. Select `Open Folder`
4. Locate `Curse/Minecraft`
4. Open `install/libraries/net/minecraftforge/forge/<version from step 1>´
5. Delete file in the folder. e.g. `forge-1.10-12.18.0.2000-1.10.0.jar`
6. Restart pack
