### ISSUE TITLE
AS2 crashes instantly

### ISSUE THREAD

**Issue by Meme-MC** [jadedcat/AS2Configs#253]
I recently downloaded from the Curse Launcher and I keep getting this error message

[16:33:37] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:33:37] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

I really want to play AS2, but don't know how to fix this, any help?

**Comment by Trisscar05** [comment]
Hum, well my first response would be to try a different launcher like soon to be legacy FTB, but I'm not certain if you can access it on there. You'd have to ask Cblair about that.

Other stuff you can check are; if you have the latest-or-close-to-version of Java 64bit, that you have 3 to 4 gigs of RAM allocated to the game (find this in the options in the curse menu for minecraft), and if you haven't already try deleting and redownloading the files.

**Comment by Developaws** [comment]
Forge corrupted on installation;

1. Write down minecraft version(we need forge version later) pack uses
2. Click `(...)` button
3. Select `Open Folder`
4. Locate `Curse/Minecraft`
4. Open `install/libraries/net/minecraftforge/forge/<version from step 1>´
5. Delete file in the folder. e.g. `forge-1.10-12.18.0.2000-1.10.0.jar`
6. Restart pack
