### ISSUE TITLE
agrarian skies 2 wont load past the launcher

### ISSUE THREAD

**Issue by Traanquil** [jadedcat/AS2Configs#259]
whenever i try to play as2 it just wont load past the launcher it just comes with this text
[09:39:00] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[09:39:00] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

i have no idea what to do. any help would be apreciated thanks!

**Comment by Trisscar05** [comment]
Back up any saves you've made, then delete/reinstall the mod pack.

**Comment by Developaws** [comment]
Corrupted forge installation;

1. Write down minecraft version(we need forge version later) pack uses
2. Click `(...)` button
3. Select `Open Folder`
4. Locate `Curse/Minecraft`
4. Open `install/libraries/net/minecraftforge/forge/<version from step 1>´
5. Delete file in the folder. e.g. `forge-1.10-12.18.0.2000-1.10.0.jar`
6. Restart pack
