### ISSUE TITLE
Just got a new laptop. cant play, keeps crashing on launch

### ISSUE THREAD

**Issue by bubbleyvamp** [jadedcat/AS2Configs#269]
I've downloaded it on a new comp and the launcher opens but after i click play it tries to load then crashes.
 
Game output _
[16:45:29] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:45:29] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
 
Launcher log
 
[16:45:22 INFO]: Minecraft Launcher 1.6.61 (through bootstrap 100) started on windows...
[16:45:22 INFO]: Current time is Sep 23, 2016 4:45:22 PM
[16:45:22 INFO]: System.getProperty('os.name') == 'Windows 8.1'
[16:45:22 INFO]: System.getProperty('os.version') == '6.3'
[16:45:22 INFO]: System.getProperty('os.arch') == 'amd64'
[16:45:22 INFO]: System.getProperty('java.version') == '1.8.0_25'
[16:45:22 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[16:45:22 INFO]: System.getProperty('sun.arch.data.model') == '64'
[16:45:22 INFO]: proxy == DIRECT
[16:45:22 INFO]: JFX is already initialized
[16:45:22 INFO]: Refreshing local version list...
[16:45:22 INFO]: Refreshing remote version list...
[16:45:22 INFO]: Refresh complete.
[16:45:22 INFO]: Loaded 1 profile(s); selected 'Agrarian Skies 2'
[16:45:22 INFO]: Refreshing auth...
[16:45:22 INFO]: Logging in with access token
[16:45:25 INFO]: Getting syncinfo for selected version
[16:45:25 INFO]: Queueing library & version downloads
[16:45:25 INFO]: Download job 'Version & Libraries' started (16 threads, 40 files)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\google\guava\guava\15.0\guava-15.0.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\tv\twitch\twitch-platform\5.16\twitch-platform-5.16-natives-windows-64.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.1\lwjgl-platform-2.9.1-natives-windows.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\google\guava\guava\17.0\guava-17.0.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\mojang\netty\1.6\netty-1.6.jar for job 'Version & Libraries'... (try 0)
[16:45:25 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Download job 'Resources' skipped as there are no files to download
[16:45:28 INFO]: Job 'Resources' finished successfully (took 0:00:00.000)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\google\guava\guava\17.0\guava-17.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\google\guava\guava\15.0\guava-15.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\mojang\realms\1.3.5\realms-1.3.5.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\tv\twitch\twitch-platform\5.16\twitch-platform-5.16-natives-windows-64.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\mojang\netty\1.6\netty-1.6.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.1\lwjgl-platform-2.9.1-natives-windows.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\tv\twitch\twitch\5.16\twitch-5.16.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Attempting to download C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\versions\1.7.10\1.7.10.jar for job 'Version & Libraries'... (try 0)
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\tv\twitch\twitch\5.16\twitch-5.16.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\mojang\realms\1.3.5\realms-1.3.5.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\versions\1.7.10\1.7.10.jar for job 'Version & Libraries': Local file matches hash, using that
[16:45:28 INFO]: Finished downloading C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar for job 'Version & Libraries': Local file matches local checksum, using that
[16:45:28 INFO]: Job 'Version & Libraries' finished successfully (took 0:00:02.772)
[16:45:28 INFO]: Launching game
[16:45:28 INFO]: Unpacking natives to C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\versions\forge-10.13.4.1492\forge-10.13.4.1492-natives-239845397736468
[16:45:28 INFO]: Launching in C:\Users\bubbl_000\Documents\Curse\Minecraft\Instances\Agrarian Skies 2
[16:45:28 INFO]: Half command: C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25\bin\javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\bubbl_000\Documents\Curse\Minecraft\Instances\Agrarian Skies 2" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Djava.library.path=C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\versions\forge-10.13.4.1492\forge-10.13.4.1492-natives-239845397736468 -cp C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\minecraftforge\forge\1.7.10-10.13.4.1492-1.7.10\forge-1.7.10-10.13.4.1492-1.7.10.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\mojang\netty\1.6\netty-1.6.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\mojang\realms\1.3.5\realms-1.3.5.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\google\guava\guava\15.0\guava-15.0.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\libraries\tv\twitch\twitch\5.16\twitch-5.16.jar;C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\versions\1.7.10\1.7.10.jar net.minecraft.launchwrapper.Launch
[16:45:28 INFO]: Looking for orphaned versions to clean up...
[16:45:28 INFO]: Looking for old natives & assets to clean up...
[16:45:29 ERROR]: Game ended with bad state (exit code 1)
[16:45:29 INFO]: Ignoring visibility rule and showing launcher due to a game crash
[16:45:29 INFO]: Deleting C:\Users\bubbl_000\Documents\Curse\Minecraft\Install\versions\forge-10.13.4.1492\forge-10.13.4.1492-natives-239845397736468

**Comment by samuelroy21** [comment]
Try a reinstall.

**Comment by Developaws** [comment]
Corrupted forge installation;

1. Write down minecraft version(we need forge version later) pack uses
2. Click `(...)` button
3. Select `Open Folder`
4. Locate `Curse/Minecraft`
4. Open `install/libraries/net/minecraftforge/forge/<version from step 1>´
5. Delete file in the folder. e.g. `forge-1.10-12.18.0.2000-1.10.0.jar`
6. Restart pack
